### ISSUE TITLE
Typo or more esoteric comp sci question?

### ISSUE THREAD

**Issue by mullingitover** [chassing/linux-sysadmin-interview-questions#14]
"Write a get_prim method in python/perl/bash/pseudo."

Is this asking for a method to find a minimum spanning tree in a weighted undirected graph (an implementation of Prim's Algorithm), or was there a typo and what you really meant to ask for was an algorithm for finding prime numbers ('get_primes' perhaps)?

**Comment by chassing** [comment]
I see :) ... I mean a function/algorithm for finding some prime numbers, you are right "get_primes" would be a better name. But anyway, questions about graphs and spanning tree would also be a possibility. feel free to submit a PR with your questions.

**Comment by dlobue** [comment]
Good grief, I spent 20 minutes googling trying to figure out what `get_prim` was, until I found this issue, LOL!
