### ISSUE TITLE
answer key

### ISSUE THREAD

**Issue by the-hobbes** [chassing/linux-sysadmin-interview-questions#22]
This is a good list of questions. Are there plans to add an answer key (and if so are you accepting pull requests for the same), or is the idea to fork this and provide your own answers?

**Comment by anuragshendge** [comment]
Seems like a good idea.

**Comment by chassing** [comment]
I believe answering all these question is a personal thing, it depends hard on the personal background, mood and so on. I don't want provide any answers here in this repo but feel free to fork it and add the answers in your personal repo.
