### ISSUE TITLE
New Questions

### ISSUE THREAD

**Issue by Homan13** [chassing/linux-sysadmin-interview-questions#43]
First off, thank you for putting this together! I've had a couple interviews recently and used this to prep for it. In going through the interview process as well as a certification course I've been taking I came up with some additional questions I thought you may like to add.

* Can you explain to me the difference between block based, and object based storage?
* What is a Linux kernel module?
* Walk me through the steps in booting into single user mode to troubleshoot a problem.
* Walk me through the steps you'd take to troubleshoot a 404 error on a web application you administer
* How would you enable network file sharing within AWS that would allow EC2 instances in multiple availability zones to share data?
* How would you take a backup of a MySQL database?

Thanks again!

**Comment by chassing** [comment]
thank you for your question. appreciate it
